version: '3.7'

networks:
  swagger:

services:
  swagger:
    image: swaggerapi/swagger-ui:v5.9.3
    volumes:
      - ../api/:/usr/share/nginx/html/api
    ports:
      - "8081:8080"
    networks:
      - swagger
    restart: unless-stopped
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      - URL=/api/openapi-release-0.0.1.yaml
