version: '3.7'

services:
  client:
    build:
      context: client/
      args:
        CLIENT_PORT: ${CLIENT_PORT}
        API_SERVER_ADDRESS: ${API_SERVER_ADDRESS}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - server

  server:
    build:
      context: server/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - roomkn
    environment:
      - DB_URL=${DB_URL:-jdbc:postgresql://db/}
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PEPPER=${PEPPER}
      - SERV_HOST=0.0.0.0
      - SERV_PORT=${SERVER_PORT}
      - SUPERUSER_NAME=${SUPERUSER_NAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}

  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_ROOT_USER:-${DB_USER}}
      - POSTGRES_PASSWORD=${DB_ROOT_USER_PASSWORD:-${DB_PASSWORD}}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - roomkn
    profiles:
      - db
      
volumes:
  db-data: {}
networks:
  roomkn:
    name: roomkn_network
    driver: bridge
