openapi: 3.0.3
info:
  title: roomkn
  description: Приложение позволяет резервировать свободные комнаты на МКН
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v0
    description: Dev server
paths:
  /rooms:
    post:
      operationId: createRoom
      security:
        - cookieAuth: []
      responses:
        201:
          description: Комната создана
          content:
            text/plain:
              schema:
                type: string
                description: Ok
                default: Ok
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        500:
          $ref: "#/components/responses/ServerError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRoom'
            example:
              name: "0404"
              description: Несуществующая комната
      summary: Создание новой комнаты
      tags:
        - rooms
    get:
      responses:
        200:
          description: Список короткой информации о всех комнатах
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ShortRoomInfo"
              example:
                - name: "0404"
        500:
          $ref: "#/components/responses/ServerError"
      summary: Получение списка короткой информации о всех комнатах
      tags:
        - rooms
  /rooms/{roomId}:
    parameters:
      - in: path
        name: roomId
        schema:
          type: integer
        required: true
        description: Id комнаты, с которой будет производится операция
    put:
      operationId: editRoomById
      security:
        - cookieAuth: []
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
          description: Комната была изменена
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        500:
          $ref: "#/components/responses/ServerError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewRoom"
      tags:
        - rooms
      summary: Изменение информации о комнате
    delete:
      operationId: deleteRoomById
      security:
        - cookieAuth: []
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
          description: Комната была удалена
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        500:
          $ref: "#/components/responses/ServerError"
      tags:
        - rooms
    get:
      operationId: getRoomById
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomInfo"
          description: Комната была удалена
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/ServerError"
      tags:
        - rooms
  /login:
    post:
      operationId: login
      summary: Авторизация и получение куки
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserInfo"
            example:
              username: admin
              password: admin
      responses:
        200:
          description: Успешно авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserId"
          headers:
            Set-Cookie:
              schema:
                $ref: "#/components/schemas/AuthSession"
        400:
          $ref: "#/components/responses/BadRequest"
      tags:
        - auth


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: auth-session
  schemas:
    NewRoom:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string
    RoomInfo:
      type: object
      required:
        - id
        - name
        - description
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
    ShortRoomInfo:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    LoginUserInfo:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    ShortUserInfo:
      type: object
      required:
        - id
        - username
      properties:
        username:
          type: string
        id:
          type: integer
    NewUserInfo:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    UpdateUserInfo:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
        email:
          type: string
    UserId:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
    UserInfo:
      type: object
      required:
        - id
        - username
        - email
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
    UserPermission:
      type: object
      description: "
        Номер: Разрешение  \n
        - 0: `ReservationsCreate`\n
        - 1: `ReservationsAdmin` \n
        - 2: `RoomsAdmin`        \n 
        - 3: `UsersAdmin`        \n 
        - 4: `GroupsAdmin`"
      required:
        - id
      properties:
        id:
          description: Номер одно из разрешений, которые есть у пользователя
          type: integer
          maximum: 4
          minimum: 0
    AuthSession:
      type: object
      description: Json веб токен
      required:
        - token
      properties:
        token:
          type: string
    NewReservation:
      type: object
      properties:
        user_id:
          type: integer
        room_id:
          type: integer
        from:
          description: ISO-8601 формат времени начала новой регистрации
          type: string
        until:
          description: ISO-8601 формат времени конца новой регистрации
          type: string
    ReservationRequest:
      type: object
      required:
        - room_id
        - from
        - until
      properties:
        room_id:
          type: integer
        from:
          description: ISO-8601 формат времени начала новой регистрации
          type: string
        until:
          description: ISO-8601 формат времени конца новой регистрации
          type: string
    Reservation:
      type: object
      required:
        - id
        - user_id
        - room_id
        - from
        - until
      properties:
        id:
          type: integer
        user_id:
          description: id пользователя, который сделал регистрацию
          type: integer
        room_id:
          description: id комнаты, для который сделана регистрация
          type: integer
        from:
          description: ISO-8601 формат времени начала регистрации
          type: string
        until:
          description: ISO-8601 формат времени конца регистрации
          type: string
  responses:
    ServerError:
      description: Внутренняя ошибка сервера
    Unauthorized:
      description: Пользователь не зарегистрирован
    BadRequest:
      description: Неправильно сформулированный запрос
    Forbidden:
      description: У пользователя нет нужного разрешения