name: Server CI
run-name: ${{ github.actor }} is running Server CI
on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server-test-action.yml'
jobs:
  Server-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        working-directory: server
        run: ./gradlew build
      - name: Run koverXml with Gradle Wrapper
        working-directory: server
        run: ./gradlew :koverXml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

