name: Server CI
run-name: ${{ github.actor }} is running Server CI
on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server-test-action.yml'
jobs:
  Server-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: cd server && ./gradlew build
      - name: Run detekt
        run: ./gradlew detekt
      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
