name: Run stress tests

on:
  push:
  workflow_dispatch:

jobs:
  Server-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run stress tests
        working-directory: server
        run: ./gradlew test --tests org.tod87et.roomkn.server.stresstests.ReservationStressTest -PrunStressTests=true

